#!/bin/sh

echo "Please input playlist URL: "
read playlistURL

echo "#!/bin/sh" > update.sh;
echo "youtube-dl -i -f \"best[height<=720]\" --download-archive archive.txt \"${playlistURL}\"" >> update.sh;
chmod +x update.sh;
./update.sh;
